/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:839201:
  appc.background(230);
} //_CODE_:window1:839201:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:488327:
  if ( paused == true ) {
    loop();
    paused = false;
    pauseButton.setText("Pause");
    pauseButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  }
  
  else {
    noLoop();
    paused = true;
    pauseButton.setText("Play");
    pauseButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  }
} //_CODE_:pauseButton:488327:

public void storeNumChanged(GSlider source, GEvent event) { //_CODE_:storeNumSlide:350746:
  storeNum = storeNumSlide.getValueI();

} //_CODE_:storeNumSlide:350746:

public void studentNumChanged(GSlider source, GEvent event) { //_CODE_:studentNumSlide:378968:
  studentNum = studentNumSlide.getValueI();
} //_CODE_:studentNumSlide:378968:

public void subjectListClicked(GDropList source, GEvent event) { //_CODE_:subjectList:304382:
  String sub = subjectList.getSelectedText();
  print(sub);
  
  if( sub.equals("Science") ) {
    //hwSlideChanged(GSlider source,GEvent);
  }
  else {
    int hwAmount, testAmount, diffAmount = 0;
  }
} //_CODE_:subjectList:304382:

public void hwSlideChanged(GSlider source, GEvent event) { //_CODE_:hwSlide:818883:
  hwAmount = hwSlide.getValueI();
} //_CODE_:hwSlide:818883:

public void testSlideChanged(GSlider source, GEvent event) { //_CODE_:testSlide:605818:
  testAmount = testSlide.getValueI();
} //_CODE_:testSlide:605818:

public void diffSlideChanged(GSlider source, GEvent event) { //_CODE_:diffSlide:657405:
  diffAmount = diffSlide.getValueI();
} //_CODE_:diffSlide:657405:

public void restartButtonClicked(GButton source, GEvent event) { //_CODE_:restartButton:589285:
  studentNum = 0;
  drawStudents();

} //_CODE_:restartButton:589285:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 444, 444, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  pauseButton = new GButton(window1, 318, 15, 80, 27);
  pauseButton.setText("Pause");
  pauseButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  storeNumSlide = new GSlider(window1, 17, 42, 152, 51, 10.0);
  storeNumSlide.setShowValue(true);
  storeNumSlide.setShowLimits(true);
  storeNumSlide.setLimits(1, 1, 5);
  storeNumSlide.setNbrTicks(5);
  storeNumSlide.setShowTicks(true);
  storeNumSlide.setNumberFormat(G4P.INTEGER, 0);
  storeNumSlide.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  storeNumSlide.setOpaque(false);
  storeNumSlide.addEventHandler(this, "storeNumChanged");
  label1 = new GLabel(window1, 41, 16, 95, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Store Number");
  label1.setOpaque(false);
  studentNumSlide = new GSlider(window1, 20, 130, 148, 40, 10.0);
  studentNumSlide.setShowValue(true);
  studentNumSlide.setShowLimits(true);
  studentNumSlide.setLimits(250, 1, 250);
  studentNumSlide.setNumberFormat(G4P.INTEGER, 0);
  studentNumSlide.setLocalColorScheme(GCScheme.RED_SCHEME);
  studentNumSlide.setOpaque(false);
  studentNumSlide.addEventHandler(this, "studentNumChanged");
  label2 = new GLabel(window1, 39, 107, 104, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Student Number");
  label2.setOpaque(false);
  subjectList = new GDropList(window1, 56, 246, 90, 140, 6, 10);
  subjectList.setItems(loadStrings("list_304382"), 0);
  subjectList.addEventHandler(this, "subjectListClicked");
  hwSlide = new GSlider(window1, 318, 235, 100, 46, 10.0);
  hwSlide.setShowValue(true);
  hwSlide.setShowLimits(true);
  hwSlide.setLimits(1, 1, 5);
  hwSlide.setShowTicks(true);
  hwSlide.setNumberFormat(G4P.INTEGER, 0);
  hwSlide.setOpaque(false);
  hwSlide.addEventHandler(this, "hwSlideChanged");
  testSlide = new GSlider(window1, 317, 312, 100, 47, 10.0);
  testSlide.setShowValue(true);
  testSlide.setShowLimits(true);
  testSlide.setLimits(1, 1, 5);
  testSlide.setShowTicks(true);
  testSlide.setNumberFormat(G4P.INTEGER, 0);
  testSlide.setOpaque(false);
  testSlide.addEventHandler(this, "testSlideChanged");
  diffSlide = new GSlider(window1, 316, 384, 100, 46, 10.0);
  diffSlide.setShowValue(true);
  diffSlide.setShowLimits(true);
  diffSlide.setLimits(1, 1, 10);
  diffSlide.setShowTicks(true);
  diffSlide.setNumberFormat(G4P.INTEGER, 0);
  diffSlide.setOpaque(false);
  diffSlide.addEventHandler(this, "diffSlideChanged");
  label3 = new GLabel(window1, 197, 323, 102, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Amount of Tests");
  label3.setOpaque(false);
  label4 = new GLabel(window1, 180, 248, 135, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Amount of Homework");
  label4.setOpaque(false);
  label5 = new GLabel(window1, 193, 398, 112, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Overall Difficulty");
  label5.setOpaque(false);
  restartButton = new GButton(window1, 319, 56, 80, 30);
  restartButton.setText("Restart");
  restartButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  restartButton.addEventHandler(this, "restartButtonClicked");
  subjects = new GLabel(window1, 59, 222, 80, 20);
  subjects.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  subjects.setText("Courses");
  subjects.setOpaque(false);
  courseDiff = new GLabel(window1, 251, 185, 106, 36);
  courseDiff.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  courseDiff.setText("Change course difficulty:");
  courseDiff.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton pauseButton; 
GSlider storeNumSlide; 
GLabel label1; 
GSlider studentNumSlide; 
GLabel label2; 
GDropList subjectList; 
GSlider hwSlide; 
GSlider testSlide; 
GSlider diffSlide; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GButton restartButton; 
GLabel subjects; 
GLabel courseDiff; 
